#### general
data:
  # VOC2012, AutoRegress
  ShapeNetPart
exp_type:
  train
do_split:
  # if True, discard previous train val test split(if any) and split 
  False
model:
  # smooth_histogram, FCN, mixture_logistics
  PCT
dataroot:
  /data

cuda:
  # if True, try to use GPU, else use CPU
  True
train_val_test_ratio:
  [0.8, 0.2, 0.0]
  # [0, 0, 1]

exp_name:
  # name of the experiment
epochs:
  100
force:
  True

#### train

lr:
  1e-3
momentum:
  0
weight_decay:
  0
batch_size:
  32
validate:
  # if True, do validation at the end of each epoch
  True
continue:
  # if True, load model from experiemnts
  False
num_samples:
  2048
