#### general
data:
  # VOC2012, AutoRegress
  VOC2012
exp_type:
  train
do_split:
  # if True, discard previous train val test split(if any) and split 
  False
model:
  # smooth_histogram, FCN
  FCN
dataroot:
  /data

cuda:
  # if True, try to use GPU, else use CPU
  True
train_val_test_ratio:
  [0.8, 0.1, 0.1]
  # [0, 0, 1]

exp_name:
  # name of the experiment
epochs:
  2
force:
  True

#### train

lr:
  0.001
momentum:
  0.9
weight_decay:
  1e-4
batch_size:
  2
validate:
  # if True, do validation at the end of each epoch
  True
continue:
  # if True, load model from experiemnts
  False
num_samples:
  2048
